version: "3"

services:
  app:
    # build section context set to current directory
    build:
      context: .
    # map port 8000 on localhost to 8000 on image
    ports:
      - "8000:8000"
    # map volume ./app on localhost to /app on image
    volumes:
      - ./app:/app
    # command that runs the app in our docker container (> allows multi-line)
    command: >
      sh -c "python manage.py wait_for_db &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword # never do this in production